#apiVersion: v1
#kind: Pod
#metadata:
#  name: frontend
#  labels:
#    app.kubernetes.io/name: frontend
#spec:
#  containers:
#    - name: frontend
#      image: nigel09/frontend

apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    app.kubernetes.io/name: catalogue
spec:
  containers:
    - name: catalogue
      image: nigel09/catalogue
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    app.kubernetes.io/name: cart
spec:
  containers:
    - name: cart
      image: nigel09/cart
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    app.kubernetes.io/name: shipping
spec:
  containers:
    - name: shipping
      image: nigel09/shipping
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
spec:
  containers:
    - name: payment
      image: nigel09/payment

---

apiVersion: v1
kind: Service
metadata:
  name: catalogue-roboshop
spec:
  selector:
    app.kubernetes.io/name: catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cart-roboshop
spec:
  selector:
    app.kubernetes.io/name: cart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-roboshop
spec:
  selector:
    app.kubernetes.io/name: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-roboshop
spec:
  selector:
    app.kubernetes.io/name: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-roboshop
spec:
  selector:
    app.kubernetes.io/name: shipping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-roboshop
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - port: 80
      targetPort: 8080
