apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  containers:
    - name: frontend
      image: rkalluru/frontend

apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    app.kubernetes.io/name: catalogue
spec:
  containers:
    - name: catalogue
      image: rkalluru/catalogue
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    app.kubernetes.io/name: cart
spec:
  containers:
    - name: cart
      image: rkalluru/cart
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    app.kubernetes.io/name: shipping
spec:
  containers:
    - name: shipping
      image: rkalluru/shipping
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
spec:
  containers:
    - name: payment
      image: rkalluru/payment